
service: registrar

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1

functions:
  registrarPlaneta:
    handler: handler.registrarPlaneta
    events:
      - http:
          path: /regplanetaapi
          method: post
    