
service: dbplaneta

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1

functions:
  mostrarPlaneta:
    handler: handler.mostrarPlaneta
    events:
      - http:
          path: /spplanetadb
          method: get
    