
service: contexto

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1

functions:
  dbcontexto:
    handler: handler.dbcontexto
    events:
      - http:
          path: /dbcontexto
          method: post